spring:
  datasource:
    url: jdbc:mysql://localhost:3306/templates?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: templates
    password: templates
    driver-class-name: com.mysql.cj.jdbc.Driver